#pragma once

#define FIRMWARE_VERSION "1.1.1"
#define FIRMWARE_NAME    "InksPet"
#define HARDWARE_PLATFORM "EleksCava Gen2"

#ifndef INKSPET_VERSION
#define INKSPET_VERSION FIRMWARE_VERSION
#endif

#define VERSION INKSPET_VERSION
